name: Windows RDP & Avica Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  setup-windows:
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python packages
        run: |
          pip install requests pyautogui telegraph

      - name: Enable RDP & Firewall
        run: |
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"

      - name: Set user password
        run: net user runneradmin TheDisa1a

      - name: Start Avica
        run: |
          Start-Process Avica_setup.exe
          python setup.py

      - name: Show Connection Info
        run: |
          call show.bat

      - name: Keep session active
        run: |
          call loop.bat
